version: '2'
services:
  db:
    image: postgres:9.6.3-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./data/redis:/data
  #   command: redis-server --appendonly yes
  web:
    environment:
      RAILS_ENV: development
      # DATABASE_URL: postgres://postgres@psql:5432
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
      # - redis
volumes:
  bundle:
    # driver: local
